### ISSUE TITLE
(PDF Downloading) Broken author info page

### ISSUE THREAD

**Issue by AaronBenDaniel** [TheOnlyWayUp/WattpadDownloader#35]
It doesn't work. Looks like template elements aren't getting properly replaced

![image](https://github.com/user-attachments/assets/b9f1a06c-5be5-4f05-8c5a-fed42a685dd3)

**Comment by TheOnlyWayUp** [comment]
Fixed on the latest commit, not a fan of how it looks tbh but it's working as expected.

![image](https://github.com/user-attachments/assets/4157b943-75ac-493e-91af-e8bf0359990c)
